//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestAcaLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Enrollment
	{
		public DateTime CancellationDate
		{
			get;
			set;
		}

		public DateTime EnrollmentDate
		{
			get;
			set;
		}

		public bool UniquePayment
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public virtual ICollection<Absence> Absences
		{
			get;
			set;
		}

		public virtual TaughtCourse TaughtCourse
		{
			get;
			set;
		}

		public virtual Student Student
		{
			get;
			set;
		}

	}
}

