//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestAcaLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class TaughtCourse
	{
		public int Quota
		{
			get;
			set;
		}

		public int SessionDuration
		{
			get;
			set;
		}

		public DateTime StartDateTime
		{
			get;
			set;
		}

		public int TotalPrice
		{
			get;
			set;
		}

		public string TeachingDay
		{
			get;
			set;
		}

		public DateTime EndTime
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public virtual Office Office
		{
			get;
			set;
		}

		public virtual Teacher Teacher
		{
			get;
			set;
		}

		public virtual ICollection<Enrollment> Enrollments
		{
			get;
			set;
		}

		public virtual Course Course
		{
			get;
			set;
		}

	}
}

