//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestAcaLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Student : Person
	{
		public string IBAN
		{
			get;
			set;
		}

		public virtual ICollection<Enrollment> Enrollments
		{
			get;
			set;
		}

	}
}

